Add heat index file for copernicus module
CLIMADA-project/climada_petals pull request #151
Opened 2024-12-05 09:53 UTC by DahyannAraya

This part of the "Copernicus Forecast Modul" that is currently under development  (see PR #142)

Changes proposed in this PR:
- Add 

This PR fixes #

### PR Author Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] Correct target branch selected (if unsure, select `develop`)
- [ ] Descriptive pull request title added
- [ ] Source branch up-to-date with target branch
- [ ] [Documentation](https://climada-python.readthedocs.io/en/latest/guide/Guide_PythonDos-n-Donts.html#Commenting-&-Documenting) updated
- [ ] [Tests][testing] updated
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_petals/blob/main/CHANGELOG.md) updated

### PR Reviewer Checklist

- [ ] Read the [Contribution Guide][contrib]
- [ ] [CLIMADA Reviewer Checklist](https://climada-python.readthedocs.io/en/latest/guide/Guide_Reviewer_Checklist.html) passed
- [ ] [Tests][testing] passing
- [ ] No new [linter issues][linter]

[contrib]: https://github.com/CLIMADA-project/climada_python/blob/main/CONTRIBUTING.md
[testing]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html
[linter]: https://climada-python.readthedocs.io/en/latest/guide/Guide_Continuous_Integration_and_Testing.html#Static-Code-Analysis

2024-12-12 13:10 UTC, ruthlorenz requested changes
Dear Dahyann,

My comments regarding the heat indices. The adjustments and filters are my main concern. If the fact that HIS is only valid for temperatures > 20 °C and otherwise not defined is a problem for CLIMADA you might need to remove it? Or at least add a comment in the class where you define the index. For HIA you need to add the filters and adjustments as in thermofeel, then you should receive a value for any temperature. However, NOAA states "The Rothfusz regression is not valid for extreme temperature and relative humidity conditions beyond the range of data considered by Steadman." The tables in Steadman (https://journals.ametsoc.org/view/journals/apme/18/7/1520-0450_1979_018_0861_taospi_2_0_co_2.xml?tab_body=pdf) go until 50 °C, which is very rare on earth. So I would add a remark in the class IndexSpecEnum.

2024-12-12 13:10 UTC, ruthlorenz commented on climada_petals/hazard/copernicus_interface/index_definitions.py
> +        explanation="Heat Index Adjusted: This indicator measures apparent temperature, considering both air temperature and humidity, providing a more accurate perception of how hot it feels.",
not valid for extreme temperature (>=50 °C) and relative humidity conditions beyond the range the equation was developed for.

2024-12-13 11:48 UTC, DahyannAraya commented on climada_petals/hazard/copernicus_interface/index_definitions.py
> +        explanation="Heat Wave: Identifies heat waves as periods with temperatures above a threshold.",
Done

2024-12-13 15:28 UTC, DahyannAraya commented on climada_petals/hazard/copernicus_interface/heat_index.py
> +    return hi
Thank you very much, Ruth, for the paper. I have applied the filter as suggested. CLIMADA can handle the NAs in this particular case without any issues. Thanks for pointing it out.

2024-12-13 16:51 UTC, DahyannAraya commented on climada_petals/hazard/copernicus_interface/heat_index.py
> +    Brimicombe, C., Bröde, P., and Calvi, P. (2022). Thermofeel: A python thermal comfort indices library. *SoftwareX*, 17, 101005. DOI: https://doi.org/10.1016/j.softx.2022.101005
Ok, done.

2024-12-13 17:01 UTC, DahyannAraya commented on climada_petals/hazard/copernicus_interface/heat_index.py
> +    e = rh / 100 * 6.105 * np.exp(17.27 * t2_c / (237.7 + t2_c))
Done

2025-01-22 10:42 UTC, DahyannAraya commented on climada_petals/hazard/copernicus_interface/index_definitions.py
> +        explanation="Heat Index Simplified: A simpler version focusing on a quick estimate of perceived heat.",
Corrected

2025-01-22 10:42 UTC, DahyannAraya commented on climada_petals/hazard/copernicus_interface/heat_index.py
> +def calculate_relative_humidity(t2_k, td_k):
Done

2025-01-22 10:43 UTC, DahyannAraya commented on climada_petals/hazard/copernicus_interface/heat_index.py
> +    return (hi - 32) * 5 / 9  # converted back to Celsius
Understood

2025-01-23 11:04 UTC, merged