Complete restructuring of the SupplyChain module
CLIMADA-project/climada_petals pull request #66
Opened 2023-01-27 16:41 UTC by aleeciu

This pull request features a complete restructuring of the supply chain module, including:
- two subtle bug fixes
- the use of pymrio (https://pymrio.readthedocs.io/en/latest/intro.html) to download and handle multi-regional input output tables
- restructuring of operations which substantially speeded the code up

Missing:
- tutorial update
- a very last check to see if it's compatible with OECD tables, otherwise erase this option

2023-01-27 16:44 UTC, aleeciu commented
Hi @emanuel-schmid, in this pull request I am using the pymrio module (https://pymrio.readthedocs.io/en/latest/index.html) which is currently not included in the CLIMADA environment. How shall I add it?

2023-01-30 10:12 UTC, emanuel-schmid commented
Yes, this problem is currently not really solved. 

There are workarounds though: one can add a line `pip install pymrio` in `script/branches/Jenkinsfile`. With this, the environment is updated before running unit-tests on Jenkins. (I just did this and the tests ran through)

However, this file should actually remain unchanged in the develop branch and `requirements/env_climada.yaml` should be changed instead. You can update env_climada.yaml anytime in this branch but it won't have an effect on the environment, which is defined by the develop branch alone. On the other hand, the changes in the Jenkinsfile be undone before or after merging. (They don't hurt but the slow down the unittests for a couple of seconds for each commit.)

For now I suggest to proceed like this and I'll clean up the Jenkinsfile after the PR has been merged.

2023-02-01 17:51 UTC, aleeciu commented
Great, thanks @emanuel-schmid for the clarification. I will then update the `requirements/env_climada.yaml` in develop after merging. One more question: I keep getting a `readthedocs error` but I am not quite sure how to fix/interpret it.

2023-02-09 08:01 UTC, aleeciu commented
> > I keep getting a readthedocs error but I am not quite sure how to fix/interpret it.
> 
> @aleeciu Try merging the latest version of `develop` back into this branch

great, it worked thanks

2023-03-29 20:51 UTC, aleeciu commented
Jenkins has been running checks for almost six hours... any clue @emanuel-schmid @peanutfun ?

2023-03-30 08:13 UTC, peanutfun commented
The latest check failed: https://ied-wcr-jenkins.ethz.ch/job/petals_branches/job/PR-66/14/ I don't know why this is not reported back to GitHub 🤔 But the check is definitely not in progress anymore 😅

2023-03-30 09:53 UTC, aleeciu commented
> The latest check failed: https://ied-wcr-jenkins.ethz.ch/job/petals_branches/job/PR-66/14/ I don't know why this is not reported back to GitHub 🤔 But the check is definitely not in progress anymore 😅

ok cool, thanks. So it seems that the following test:
`climada_petals.engine.test.test_supplychain.TestSupplyChain.test_indirect_production_impact`
is failing, right? 

But it does not when I run it on my machine, and I really don't understand why. Does Jenkins gives fail if the test throws a `warning`?

2023-03-30 10:04 UTC, emanuel-schmid commented
No, it doesn't. But it [tells](https://ied-wcr-jenkins.ethz.ch/job/petals_branches/view/change-requests/job/PR-66/14/testReport/junit/climada_petals.engine.test.test_supplychain/TestSupplyChain/test_indirect_production_impact/) you what the problem is:

```
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/petals_branches/branches/PR-66/workspace/climada_petals/engine/test/test_supplychain.py", line 175, in test_indirect_production_impact
    self.assertAlmostEqual(sup.indir_prod_impt_mat.values.sum(), 7093283110973.164, places=3)
AssertionError: 7093283110973.162 != 7093283110973.164 within 3 places (0.001953125 difference)
```

These rounding differences are quite common and the reason could be anything from dependency library over compiler to processor, afaik. On the bright side: easy to fix 😁

2023-03-30 11:15 UTC, aleeciu commented
thanks for your hints - I fixed it now - although I am pretty sure @peanutfun will request extensive changes to these tests :-)

2023-04-06 16:37 UTC, peanutfun requested changes
I found a lot of small issues, but overall, this is looking good! 🙌  I have a few general comments:

* The tutorial seems to work well and gives a nice overview. However, most computed values seem to be zero. It would be great if you could adapt the tutorial to focus on a particularly impacted sector, in order for readers to literally *see something* (most displayed data frames only show zeros).
* I do not understand the tests as they rely on real data. Can you add tests where you use self-made, dummy data for testing the calculations?
* The `SupplyChain` class mostly stores computed data in attributes and uses these attributes in the logically following calculation. But many of these calculations never check if the attribute actually exists. This will lead to weird errors if the methods are called in the wrong order. I would prefer returning the values to the user and then having the user insert them in the next function. This ensures that the data required for the calculation is always there.
* Many methods and functions are named `calc_XYZ`. I personally would prefer removing this prefix. It is usually clear that the functions calculate something. This way, the names get shorter and less abbreviations need to be used.
* Several functions try to work with both numpy and pandas data structures. It feels to me like this may introduce subtle bugs that are difficult to test and debug. Is this at all necessary?

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +            warnings.simplefilter("ignore")
Only ignore the divide by zero warning
```suggestion
            # Ignore devide by zero warning, we set to 0 afterwards
            warnings.filterwarnings("ignore", message="divide by zero")
```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        recix[recix == np.inf] = 0
Test for negative inf as well?
```suggestion
        recix[recix.isinf()] = 0
```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        recix = recix.reshape((-1, 1))
Seems unnecessary given the broadcasting rules. Tests pass without this line.
```suggestion
```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        return pd.DataFrame(Z.values * recix, index=Z.index, columns=Z.columns)
```suggestion
        return pd.DataFrame(Z.to_numpy() * recix, index=Z.index, columns=Z.columns)
```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        The type is determined by the type of G. If DataFrame index as G
```suggestion
        Industry output x as column vector.
        Same type as input parameter ``G``.
```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +    return mriot
Variable possibly unbound here
```suggestion
    else:
        raise RuntimeError(f"Unknown mriot_type: {mriot_type}")

    return mriot
```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        self.indir_prod_impt_eai = self.indir_prod_impt_mat.T.dot(impact.frequency)
Same as above, why not return the value?

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        self.tot_prod_impt_eai = self.tot_prod_impt_mat.T.dot(impact.frequency)
Same as above, why not expect `<in>dir_prod_impt_mat` as arguments? This method never checks if the attributes are really set.

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        stock_to_prod_shock=None,
Please add documentation for these parameters

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        """
Please add documentation for `io_approach` parameter

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +    def conv_fac(self):
Unnecessary abbreviation?
```suggestion
    def conversion_factor(self):
```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +
Need to handle unknown approach?

```suggestion
        else:
            raise RuntimeError(f"Unknown io_approach: {io_approach}")

```

2023-04-06 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +            tot_imp_reg_id = impact.imp_mat[:, np.where(exp_bool)[0]].sum(1)
`Impact.impact_at_reg` is available now!

2023-05-08 08:59 UTC, peanutfun commented
@aleeciu How do we proceed here?

2023-05-08 10:40 UTC, peanutfun commented
> Also, there is a fork of this fork https://github.com/CLIMADA-project/climada_petals/tree/feature/climada_boario and I am torned whether adding those changes to this PR or not.

@aleeciu The smaller the changes, the better. I see no conflicts between the `supplychain` and `climada_boario` branches.  I suggest merging this PR first. After that, reviewing `climada_boario` separately should be much easier.

2023-05-17 13:20 UTC, aleeciu commented on climada_petals/engine/supplychain.py
> +            Expected total production impact for each country and sector
After a bilateral discussion with @peanutfun , we decided not to implement this since indeed some - but not all - DataFrames have the same structure

2023-06-01 16:48 UTC, aleeciu commented
I updated the branch based on the inputs from @peanutfun (and also applied some other changes but nothing major):

- better tutorial, no zeros everywhere and I hope more detailed explanation
- better tests, when I could I built dummy tables and checked results against expected ones. In some cases - however - operations are not straightforward and I would not know what to do rather than rewriting code to have these "expected" results
- rewrote the docstring and cleaned up all the unused / undeclared attributed
- I am getting some test errors on Jenkins (but not locally) - but if I understand they are not related to the module develop in this pull-request (https://ied-wcr-jenkins.ethz.ch/job/petals_branches/view/change-requests/job/PR-66/lastCompletedBuild/testReport/)

On my side - I'd inclined to say we are there, but of course happy to get more feedbacks.

2023-06-02 07:52 UTC, peanutfun commented
Thanks a lot @aleeciu! I'll have another thorough look next week

2023-10-10 16:33 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +    if (type(x) is not np.ndarray) and (x == 0):
```suggestion
    if not isinstance(x, np.ndarray) and (x == 0):
```

2023-10-10 16:35 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        Tuple of integers with positions of rows
```suggestion
        Tuple of integers with positions of rows
```

2023-10-10 16:35 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        Tuple of integers with positions of columns
```suggestion
        Tuple of integers with positions of columns
```

2023-10-10 16:36 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +    elif mriot_type == "WIOD16":
```suggestion
    if mriot_type == "WIOD16":
```

2023-10-10 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        raise ValueError("Unknown MRIOT type")
```suggestion
    raise ValueError("Unknown MRIOT type")
```

2023-10-10 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +    """Download EXIOBASE3, WIOD16 or OECD21 Multi-Regional Input Output Tables
```suggestion
    """Download EXIOBASE3, WIOD16 or OECD21 Multi-Regional Input Output Tables
```

2023-10-10 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +    for specific years.
```suggestion
    for specific years.
```

2023-10-10 16:37 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +            Exposure dataframe of each country/sector in the MRIOT. Columns are the
```suggestion
            Exposure dataframe of each country/sector in the MRIOT. Columns are the
```

2023-10-10 16:38 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +            Columns are the same as the chosen MRIOT and rows are the hazard events ids.
```suggestion
            Impact dataframe for the directly affected countries/sectors for each event with
            impacts. Columns are the same as the chosen MRIOT and rows are the hazard events ids.
```

2023-10-10 16:38 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +            and values the Leontief (L, if approach is leontief or eeioa) or Ghosh (G, if
```suggestion
            and values the Leontief (L, if approach is leontief or eeioa) or Ghosh (G, if
```

2023-10-10 16:38 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        """Download, parse and read WIOD16, EXIOBASE3, or OECD21 Multi-Regional
```suggestion
        """Download, parse and read WIOD16, EXIOBASE3, or OECD21 Multi-Regional
```

2023-10-10 16:38 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +                              impacted_secs=None,
```suggestion
    def calc_shock_to_sectors(self,
                              exposure,
                              impact,
                              impacted_secs=None,
```

2023-10-10 16:38 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        This function translate spatially-distrubted exposure and impact
```suggestion
        This function translate spatially-distrubted exposure and impact
```

2023-10-10 16:38 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        information into exposure and impact of MRIOT's country/sectors and
```suggestion
        information into exposure and impact of MRIOT's country/sectors and
```

2023-10-10 16:39 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        """Build technical coefficient and Leontief inverse matrixes
```suggestion
        """Build technical coefficient and Leontief inverse matrixes
```

2023-10-10 16:39 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        (if leontief or eeioa approach) or allocation coefficients and
```suggestion
        (if leontief or eeioa approach) or allocation coefficients and
```

2023-10-10 16:39 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        """Calculate indirect production impacts based on to the
```suggestion
        """Calculate indirect production impacts based on to the
```

2023-10-10 16:39 UTC, peanutfun commented on climada_petals/engine/supplychain.py
> +        return mriot_reg_name
```suggestion
        return mriot_reg_name

```

2023-10-13 14:13 UTC, aleeciu commented
Many thanks @peanutfun; I am confused because I saw some suggested changes from your side but now they are marked as resolved. It's all good for me if you implemented them directly, just please let me know if changes are still expected from my side.

ps
I did not mean to urge you few days ago by reminding you about the review - I just pressed the button by mistake :-)

2023-10-13 15:18 UTC, peanutfun commented
@aleeciu I now marked the comments as resolved. Some were outdated and for others I am not familiar enough with the module to mess with it now. If you are fine with how it works, I think we can merge 🙂

2023-10-13 15:26 UTC, aleeciu commented
we can merge from my side, and we still have #81 which will bring changes to this module

2023-11-08 10:47 UTC, merged