changelog and pr-template
CLIMADA-project/climada_petals pull request #72
Opened 2023-03-14 13:49 UTC by emanuel-schmid

analogous to climada_python

2023-03-14 13:52 UTC, emanuel-schmid commented
to be discussed March 15 😄

2023-03-14 18:45 UTC, leonie-villiger requested changes
I like! Thanks for adding, but yes let`s see what results from the discussion on 15 March. In case we decide to add the CHANGELOG for python_petals there is one link to be adapted. Apart from that everything looks fine to me.

2023-03-14 18:45 UTC, leonie-villiger commented on .github/pull_request_template.md
> +- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated
```suggestion
- [ ] [Changelog](https://github.com/CLIMADA-project/climada_petals/blob/main/CHANGELOG.md) updated
```

2023-03-14 21:33 UTC, emanuel-schmid commented on .github/pull_request_template.md
> +- [ ] [Changelog](https://github.com/CLIMADA-project/climada_python/blob/main/CHANGELOG.md) updated
😊

2023-03-15 06:12 UTC, leonie-villiger approved these changes

2023-03-20 11:00 UTC, peanutfun requested changes

2023-03-20 11:00 UTC, peanutfun commented on CHANGELOG.md
> +- PR Template bassed on climada_python .github/pull_request_template.md [#72](https://github.com/CLIMADA-project/climada_petals/pull/72)
I think this should be a single entry per PR:
```suggestion
- Changelog and PR description template based on the Climada Core repository [#72](https://github.com/CLIMADA-project/climada_petals/pull/72)
```

2023-03-20 12:15 UTC, emanuel-schmid commented
@peanutfun : good catch!

2023-03-20 16:20 UTC, leonie-villiger commented
> Thanks! ☺️
> 
> > Thanks for adding, but yes let`s see what results from the discussion on 15 March.
> 
> @leonie-villiger, what was discussed and what was the result? 😅 I think this is good to go and I'll leave you the honors of merging, if your discussion did not come to a different conclusion

The PR was added before _adding a CHANGELOG.md to climada_petals_ was discussed in a climada call. That`s why I wrote "let`s see what results from the discussion". I didn`t participate in this particular climada call but the meeting indicate that the suggestion was approved. Therefore, I will now - with great pleasure - merge this PR ☺️

2023-03-20 16:20 UTC, merged